#! /bin/bash
export TERM="xterm-256color"

### https://github.com/mavnn/mintty-colors-solarized
if [[ -e ~/.zsh/extras/mintty-colors-solarized/sol.dark ]] ; then
	source ~/.zsh/extras/mintty-colors-solarized/sol.dark
fi

### https://github.com/seebi/dircolors-solarized
if [[ -e ~/.zsh/extras/dircolors-solarized/dircolors.ansi-dark ]] ; then
	eval `dircolors ~/.zsh/extras/dircolors-solarized/dircolors.ansi-dark`
fi

# Set PATH so it includes /usr/local/sbin if it exists
if [ -d "/usr/local/sbin" ] ; then
 PATH="/usr/local/sbin:${PATH}"
fi

# Set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
 PATH="$HOME/bin:${PATH}"
fi

# Set PATH so that it includes unix-tools project bin
if [ -d "$HOME/bin/unix-tools" ] ; then
        PATH="$HOME/bin/unix-tools:${PATH}"
fi

# Set PATH so that it includes work-tools project bin
if [ -d "$HOME/bin/work/unix-tools" ] ; then
        PATH="$HOME/bin/work/unix-tools:${PATH}"
fi

# Set PATH so that it includes MY private bin
if [ -d "$HOME/.zsh/bin" ] ; then 
	PATH="$HOME/.zsh/bin:${PATH}"
fi

export HISTFILE=~/.zsh/history
setopt INC_APPEND_HISTORY
export SAVEHIST=3000
setopt HIST_EXPIRE_DUPS_FIRST
export HISTSIZE=1000

# Make sure nano highlighting is turned on
if [[ -e ~/.nanorc ]] ; then
	if ! cat .nanorc | grep "include /usr/share/nano/sh.nanorc" > /dev/null ; then
		if [[ -e /usr/share/nano/sh.nanorc ]] ; then
			echo include /usr/share/nano/sh.nanorc >> ~/.nanorc
		fi
	fi
else
	touch ~/.nanorc
	echo include /usr/share/nano/sh.nanorc >> ~/.nanorc
fi


# Completions
if [ -d ~/.zsh/completion ] ; then
	fpath=(~/.zsh/completion $fpath)
fi


autoload -Uz compinit promptinit
compinit -d ~/.zsh/compdump
promptinit

#autoload bashcompinit

#if [ -e ~/.zsh/completion/bash/* ] ; then
#	source ~/.zsh/completion/bash/*
#fi

# Keybinds
# ctrl-left/right
bindkey "\e[1;5C" forward-word
bindkey "\e[1;5D" backward-word

# ctrl-backspace/delete
#bindkey "\C-_" backward-kill-word
#bindkey "\e[3;5~" kill-word

# alt-backspace
#bindkey "\e\d" undo

bindkey "\e[3~" delete-char
bindkey '\e[H' beginning-of-line
bindkey '\e[F' end-of-line


alias rm='rm -i'
alias ls='ls -F --group-directories-first --color=tty'
#alias grep='grep --color=always'

#irccert='sudo su -l weechat -c "irccert $1"'

# Some example alias instructions
# If these are enabled they will be used instead of any instructions
# they may mask.  For example, alias rm='rm -i' will mask the rm
# application.  To override the alias instruction use a \ before, ie
# \rm will call the real rm not the alias.
#
# Interactive operation...
# alias rm='rm -i'
# alias cp='cp -i'
# alias mv='mv -i'
#
# Default to human readable figures
# alias df='df -h'
# alias du='du -h'
#
# Misc :)
# alias less='less -r'                          # raw control characters
# alias whence='type -a'                        # where, of a sort
# alias grep='grep --color'                     # show differences in colour
# alias egrep='egrep --color=auto'              # show differences in colour
# alias fgrep='fgrep --color=auto'              # show differences in colour
#
# Some shortcuts for different directory listings
# alias ls='ls -hF --color=tty'                 # classify files in colour
# alias dir='ls --color=auto --format=vertical'
# alias vdir='ls --color=auto --format=long'
# alias ll='ls -l'                              # long list
# alias la='ls -A'                              # all but . and ..
# alias l='ls -CF'                              #
