#! /bin/bash
export TERM="xterm-256color"
export MDV_THEME=960.847

# Don't save lines with leading spaces
setopt histignorespace
# Don't save duplicates of a command
setopt HIST_SAVE_NO_DUPS

### https://github.com/mavnn/mintty-colors-solarized
#if [[ -e ${HOME}/.zsh/extras/mintty-colors-solarized/sol.dark ]] ; then
#	source ${HOME}/.zsh/extras/mintty-colors-solarized/sol.dark
#fi

### https://github.com/seebi/dircolors-solarized
if [[ -e ${HOME}/.zsh/extras/dircolors-solarized/dircolors.ansi-dark ]] ; then
	eval `dircolors ${HOME}/.zsh/extras/dircolors-solarized/dircolors.ansi-dark`
fi

# Set PATH so it includes /usr/local/sbin if it exists
if [ -d "/usr/local/sbin" ] ; then
 PATH="/usr/local/sbin:${PATH}"
fi

# Set PATH so it includes user's private bin if it exists
if [ -d "${HOME}/bin" ] ; then
 PATH="${HOME}/bin:${PATH}"
fi

# Set PATH so that it includes unix-tools project bin
if [ -d "${HOME}/bin/unix-tools" ] ; then
	PATH="${HOME}/bin/unix-tools:${PATH}"
fi

# Set PATH so that it includes work-tools project bin
if [ -d "${HOME}/bin/work/unix-tools" ] ; then
	PATH="${HOME}/bin/work/unix-tools:${PATH}"
fi
if [ -d "${HOME}/bin/work" ] ; then
	PATH="${HOME}/bin/work:${PATH}"
fi

# Set PATH so that it includes MY private bin
if [ -d "${HOME}/.zsh/bin" ] ; then
	PATH="${HOME}/.zsh/bin:${PATH}"
fi

if [ -d "${HOME}/Dockerfiles/bin" ] ; then
	PATH="${HOME}/Dockerfiles/bin:${PATH}"
fi

# Set PATH so that it includes go programs installed to ~/go/bin, if present
if [ -d "~/go/bin" ] ; then
 PATH="~/go/bin:${PATH}"
fi


export HISTFILE=${HOME}/.zsh/history
setopt INC_APPEND_HISTORY
export SAVEHIST=3000
setopt HIST_EXPIRE_DUPS_FIRST
export HISTSIZE=1000

# Make sure nano highlighting is turned on

if [[ ! -e ${HOME}/.nanorc ]] ; then
	ln -s "${HOME}/.zsh/extras/nanorc.custom" "${HOME}/.nanorc"
fi

## Syntax files from https://github.com/scopatz/nanorc
#if [[ ! -e ${HOME}/.nanorc ]] ; then
#	touch ${HOME}/.nanorc
#fi

#if ! cat ${HOME}/.nanorc | grep "set nowrap" > /dev/null ; then
#	echo "set nowrap" >> ${HOME}/.nanorc
#fi

#if ! grep -f ~/.zsh/extras/nanorc.custom ~/.nanorc > /dev/null ; then
#	cat ~/.zsh/extras/nanorc.custom >> ~/.nanorc
#fi


if [[ ! -e ${HOME}/.gitconfig ]] ; then
	touch ${HOME}/.gitconfig
fi

if ! grep -f ~/.zsh/ref/gitconfig ~/.gitconfig > /dev/null ; then
	echo "Adding contents of '~/.zsh/ref/gitconfig' to '~/.gitconfig'"
	cat ~/.zsh/ref/gitconfig >> ~/.gitconfig
fi

# Functions

if [ -d ~/.zsh/functions ] ; then
	for f in ~/.zsh/functions/* ; do source $f; done
fi

# Completions
if [ -d ${HOME}/.zsh/completion ] ; then
	fpath=(${HOME}/.zsh/completion $fpath)
fi

autoload -Uz compinit promptinit
compinit -d ${HOME}/.zsh/compdump
promptinit

#autoload bashcompinit

#if [ -e ${HOME}/.zsh/completion/bash/* ] ; then
#	source ${HOME}/.zsh/completion/bash/*
#fi

# Keybinds
# ctrl-left/right
bindkey "\e[1;5C" forward-word
bindkey "\e[1;5D" backward-word

# ctrl-backspace/delete
#bindkey "\C-_" backward-kill-word
#bindkey "\e[3;5~" kill-word

# alt-backspace
#bindkey "\e\d" undo

bindkey "\e[3~" delete-char
bindkey '\e[H' beginning-of-line
bindkey '\e[F' end-of-line

if hub --version > /dev/null 2>&1 ; then
	eval "$(hub alias -s)"
fi

#alias nano='nano--tabsize=4 --linenumbers --wordbounds --softwrap --constantshow'
nanohelp=$(nano --help)
nanolist=("--linenumbers" "--wordbounds" "--softwrap" "--constantshow")
for i in "${nanolist[@]}" ; do
	echo "$nanohelp" | grep --silent "\\$i"
	if [ $? -eq 0 ] ; then
		nanoargs="${nanoargs} ${i}"
	fi
done
echo "$nanohelp" | grep --silent "\--tabsize"
if [ $? -eq 0 ] ; then
	nanoargs="${nanoargs} --tabsize=4"
fi
alias nano="nano ${nanoargs}"


alias rm='rm -i'
alias ls='ls -F --group-directories-first --color=tty'
alias diff="git diff --no-index --color-words"

alias wanip='dig +short myip.opendns.com @resolver1.opendns.com'

#-> Force allocation of a tty
alias ssh='ssh -t'

#alias grep='grep --color=always'

#irccert='sudo su -l weechat -c "irccert $1"'

# Some example alias instructions
# If these are enabled they will be used instead of any instructions
# they may mask. For example, alias rm='rm -i' will mask the rm
# application. To override the alias instruction use a \ before, ie
# \rm will call the real rm not the alias.
#
# Interactive operation...
# alias rm='rm -i'
# alias cp='cp -i'
# alias mv='mv -i'
#
# Default to human readable figures
# alias df='df -h'
# alias du='du -h'
#
# Misc :)
# alias less='less -r'                          # raw control characters
# alias whence='type -a'                        # where, of a sort
# alias grep='grep --color'                     # show differences in colour
# alias egrep='egrep --color=auto'              # show differences in colour
# alias fgrep='fgrep --color=auto'              # show differences in colour
#
# Some shortcuts for different directory listings
# alias ls='ls -hF --color=tty'                 # classify files in colour
# alias dir='ls --color=auto --format=vertical'
# alias vdir='ls --color=auto --format=long'
# alias ll='ls -l'                              # long list
# alias la='ls -A'                              # all but . and ..
# alias l='ls -CF'                              #
