#! /bin/bash
### https://github.com/romkatv/powerlevel10k
if [[ -e ~/.zsh/extras/powerlevel10k/powerlevel10k.zsh-theme ]] ; then
	source ~/.zsh/extras/powerlevel10k/powerlevel10k.zsh-theme
fi

if [[ -e /var/www/html/owncloud/occ ]] ; then
	alias occ="sudo -uapache /var/www/html/owncloud/occ"
fi
alias apt-search="dpkg-query -L"
alias composer="sudo -uapache composer"

if [ -e /etc/motd ] ; then
	cat /etc/motd
fi

#-> https://stackoverflow.com/a/18915067
SSH_ENV="$HOME/.ssh/environment"

function start_agent {
    echo "Initialising new SSH agent..."
    /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
    echo succeeded
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
    /usr/bin/ssh-add;
}

# Source SSH settings, if applicable

if [ -f "${SSH_ENV}" ]; then
    . "${SSH_ENV}" > /dev/null
    #ps ${SSH_AGENT_PID} doesn't work under cywgin
    ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
        start_agent;
    }
else
    start_agent;
fi


# Import the navi widget, if it's available
#-> https://stackoverflow.com/a/677212/1871306
if hash navi 2>/dev/null ; then
	source <(navi widget zsh)
fi
