#! /bin/bash
source ~/.zsh/powerlevel9k/powerlevel9k.zsh-theme
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir rbenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator ip disk_usage load ram)
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
#POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="↱"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="↳ "
#POWERLEVEL9K_COLOR_SCHEME='light'
POWERLEVEL9K_DISK_USAGE_BACKGROUND='blue'


if [[ -e /var/www/html/owncloud/occ ]] ; then
	alias occ="sudo -uapache /var/www/html/owncloud/occ"
fi
